version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    volumes:
      - /var/lib/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database_dev
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      TZ: America/Sao_Paulo
      PGTZ: GMT-3

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres
